# Generated by Django 3.1.5 on 2021-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='carts', to='ecommerce.PurchasingItem'),
        ),
    ]
